apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-democsishare-nfs
  namespace: nom-namespace
  labels:
    application: nfs
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      application: nfs
  template:
    metadata:
      labels:
        application: nfs
    spec:
      containers:
      - name: demo-nginx-democsishare-nfs
        image: nginx:1.27
        resources:
          requests:
            memory: "8Mi"
            cpu: "250m"
          limits: 
            memory: "256Mi"
            cpu: 1  
        livenessProbe:
          initialDelaySeconds: 5 
          periodSeconds: 5 
          exec:
           command:
           - ls /usr/share/nginx/html
        ports:
        - containerPort: 80
        volumeMounts:
            - name: pv-democsishare-nfs
              mountPath: "/usr/share/nginx/html"
      volumes:
        - name: pv-democsishare-nfs
          persistentVolumeClaim:
            claimName: pvc-democsishare-nfs
  
   
