---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: nfs.csi.k8s.io
  name: pv-acme2certifier-default
  namespace: inf-cert-lan
  labels:
    environment: prd
    network: lan
    app: acme2certifier
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: emplacement_nfs_a_definir/acme2certifier
    volumeAttributes:
      server: IP.DU.NAS.NFS
      share: emplacement_nfs_a_definir/acme2certifier