---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-cme2certifier-default
  namespace: inf-cert-lan
  labels:
    environment: prd
    network: lan
    application: acme2certifier
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: pv-acme2certifier-default
  storageClassName: ""