apiVersion: apps/v1
kind: Deployment
metadata:
  name: acme2certifier
  namespace: inf-cert-lan
  labels:
    environment: prd
    network: lan
    app: acme2certifier
spec:
  replicas: 1
  selector:
    matchLabels:
      environment: prd
      network: lan
      app: acme2certifier
  template:
    metadata:
      labels:
        environment: prd
        network: lan
        app: acme2certifier
    spec:
      containers:
      - name: acme2certifier
        image: grindsa/acme2certifier:0.36-nginx-wsgi
        ports:
        - containerPort: 80
        volumeMounts:
              - name: pv-democsishare-nfs
                mountPath: "/var/www/acme2certifier/config"
              - name: acme2certifier-conf
                mountPath: "/var/www/acme2certifier/acme_srv/acme_srv.cfg" 
                subPath: acme_srv.cfg 
      volumes:
        - name: acme2certifier-conf
          configMap:
            name: cm-acme2certifier
        - name: pv-democsishare-nfs
          persistentVolumeClaim:
            claimName: pvc-cme2certifier-default   
