---
  kind: Service
  apiVersion: v1
  metadata:
    name: svc-acme2certifier-default
    namespace: inf-cert-lan
    labels:
      environment: prd
      network: lan
      application: acme2certifier
  spec:
    ports:
      - name: http
        port: 80
        protocol: TCP
        targetPort: 80
    selector:
      environment: prd
      network: lan
      app: acme2certifier
  