apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-demoacme2certifier-front
  namespace: dev-demoacme2certifier-lan
  labels:
    environment: dev
    network: lan
    application: demoacme2certifier
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      environment: dev
      network: lan
      application: demoacme2certifier
  template:
    metadata:
      labels:
        environment: dev
        network: lan
        application: demoacme2certifier
    spec:
      containers:
      - name: demo-nginx-traefik-lan
        image: nginx:1.27
        resources:
          requests:
            memory: "8Mi"
            cpu: "250m"
          limits: 
            memory: "256Mi"
            cpu: 1  
        ports:
        - containerPort: 80
   
