#####Variables systeme
var_ntp_server: ntp.serveur.domain
var_domain: "domain.suffixe"
#variable user
var_admin_user: user_admin

######Variables Packages
#Liste des paquets à déployer sur les control plane
var_k8s_packages_master:
  - kubeadm-{{ var_kub_version }}
  - nfs-utils
  - wget
  - tar
  - kubectl-{{ var_kub_version }}
  - kubelet-{{ var_kub_version }}
  - jq
  - git
  - runc

#Liste des paquets à déployer sur les nodes
var_k8s_packages_worker:
  - kubeadm-{{ var_kub_version }}
  - nfs-utils
  - wget
  - tar
  - kubelet-{{ var_kub_version }}
  - runc

#Liste des paquets à supprimer  
var_remove_packages:
 - docker
 - containerd  

###############Variable Kubernetes
#Variables utilisées pour construire le fichier de configuration de kubeadm basé sur le template kubeadm.conf.j2 du dossier templates
var_api_version: v1beta3
var_kub_version : "1.30.5"
var_kub_name: kub
var_pod_subnet: "10.11.0.0/16"
var_service_subnet: "10.12.0.0/16"
var_vip_kub_endpoint: kub.coolcorp.priv
var_vip_kub_vip: "192.168.10.91"
var_vip_kub_vip_dmz: "192.168.5.91"


#Variables définissant les ports à ouvrir
#- ports "system" pour kubernetes 
var_kubelet_port: 10250
var_kube_api_port: 6443
var_etcd_port: 2379
var_etcd_member_port: 2380
var_node_service_port: "30000-32767"


var_cilium_udp_vxlan_port: 8472
var_cilium_tcp_healt_port: 4240
var_cilium_tcp_obser_port: 4222
var_cilium_tcp_relay_port: 4245
var_cilium_tcp_hubblepeer_port: 4244

#Configuration de Cilium
var_cilium_subnet: "10.13.0.0/16"
var_cilium_cli: "https://github.com/cilium/cilium-cli/releases/latest/download/cilium-linux-amd64.tar.gz"

#Lien vers la récupération du binaire containerd
var_containerd_binary: https://github.com/containerd/containerd/releases/download/v1.7.16/containerd-1.7.16-linux-amd64.tar.gz




