apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-democsishare-smbsub
  namespace: nom-namespace
  labels:
    application: smb
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      application: smb
  template:
    metadata:
      labels:
        application: smb
    spec:
      containers:
      - name: demo-nginx-democsishare-smb
        image: nginx:1.27
        resources:
          requests:
            memory: "8Mi"
            cpu: "250m"
          limits: 
            memory: "256Mi"
            cpu: 1  
        livenessProbe:
          initialDelaySeconds: 5 
          periodSeconds: 5 
          exec:
           command:
           - ls /usr/share/nginx/html
        ports:
        - containerPort: 80
        volumeMounts:
            - name: pv-democsishare-smb
              mountPath: "/usr/share/nginx/html"
              subPath: subfolder
      volumes:
        - name: pv-democsishare-smb
          persistentVolumeClaim:
            claimName: pvc-democsishare-smb
  
   
