apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-vm-demo-dmz
  namespace: dev-demovm-dmz
  labels:
    environment: dev
    network: dmz
    application: kubevirt
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: sc-local-storage-prddtsnme001
  resources:
    requests:
      storage: 30Gi



