---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: smb.csi.k8s.io
  name: pv-democsishare-smb
  namespace: nom-namespace
  labels:
    application: smb
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: //serveur-smb/smbshare/
    volumeAttributes:
      source: //serveur-smb/smbshare/
    nodeStageSecretRef:
      name: secret-smb-default
      namespace: inf-smb-lan      