---
  kind: Service
  apiVersion: v1
  metadata:
    name: svc-democsishare-smb
    namespace: nom-namespace
    labels:
      application: smb
  spec:
    ports:
      - name: http
        port: 80
        protocol: TCP
        targetPort: 80
    selector:
      application: smb
