---
- name: Install basic packages 
  become: yes 
  tdnf:
    update_cache: yes
    name: "etcd"
    state: present
  tags: role_k8s_etcd_backup.prerequis.package
  when: "'k8sctp' in inventory_hostname"

- name: Creates backup folder
  become: yes
  file:
    path: "/etc/kubernetes/backup"
    state: directory
    mode: 0770 
    recurse: yes
  when: "'k8sctp' in inventory_hostname"
  tags: role_k8s_etcd_backup.etcd.folder

- name: Creates restore folder
  become: yes
  file:
    path: "/etc/kubernetes/restore"
    state: directory
    mode: 0770 
    recurse: yes
  when: "'k8sctp' in inventory_hostname"
  tags: role_k8s_etcd_backup.etcd.folder
