---
- name: Récupérer l'adresse IPv4 de l'interface eth0
  become: yes
  shell: ip -4 addr show dev eth0 | grep inet | awk '{print $2}' | cut -d'/' -f1
  register: ipv4_address_eth0
  when: "'k8sctp' in inventory_hostname"
  tags: role_k8s_etcd_backup.script.ip

- name: Afficher l'adresse IPv4 associée à eth0
  debug:
    msg: "L'adresse IPv4 de l'interface eth0 est {{ ipv4_address_eth0.stdout }}"
  when: "'k8sctp' in inventory_hostname"
  tags: role_k8s_etcd_backup.script.ip


- name: "Deploy ETCD Backup script"
  become: yes 
  template:
    src: backup-etcd.sh.j2
    dest: /etc/kubernetes/backup/backup-etcd.sh
    mode: u=rwx,g=r,o=r
  when: "'k8sctp' in inventory_hostname"
  tags: role_k8s_etcd_backup.script.copy


  
